-- luaxml_script_Guide_EquipMake
local luaxml_script_Guide_EquipMake = {
	["1000"] = {
		["actor"] = "main",
		["next"] = "1001",
		["param"] = "",
		["action"] = "start",
		["type"] = "Story",
		["id"] = "1000",
	},
	["1001"] = {
		["action"] = "hideC",
		["type"] = "MainUI",
		["id"] = "1001",
		["actor"] = "main",
		["next"] = "1002",
	},
	["1002"] = {
		["actor"] = "me",
		["next"] = "1003",
		["param"] = "2",
		["action"] = "controlC",
		["type"] = "Player",
		["id"] = "1002",
	},
	["1003"] = {
		["actor"] = "main",
		["next"] = "1004",
		["delay"] = "1",
		["param"] = "429000",
		["action"] = "buildC",
		["type"] = "Camera_C",
		["id"] = "1003",
	},
	["1004"] = {
		["actor"] = "main",
		["next"] = "1005;1006",
		["delay"] = "1",
		["param"] = "429000",
		["action"] = "clickBuildC",
		["type"] = "Build_C",
		["id"] = "1004",
	},
	["1005"] = {
		["actor"] = "me",
		["delay"] = "1.5",
		["param"] = "1",
		["action"] = "controlC",
		["type"] = "Player",
		["id"] = "1005",
	},
	["1006"] = {
		["actor"] = "main",
		["next"] = "1007",
		["delay"] = "1",
		["param"] = "UI_AREA_429000_PUW_1|1|5001",
		["action"] = "clickC",
		["type"] = "Arrow",
		["id"] = "1006",
	},
	["1007"] = {
		["action"] = "showC",
		["type"] = "MainUI",
		["id"] = "1007",
		["actor"] = "main",
		["next"] = "1008",
	},
	["1008"] = {
		["actor"] = "me",
		["next"] = "1009;1010",
		["param"] = "2",
		["action"] = "controlC",
		["type"] = "Player",
		["id"] = "1008",
	},
	["1009"] = {
		["condtion"] = "return getStorySysData('dy_guideGrowLocalCloseTalk')==0",
		["param"] = "UI_AREA_EquipForge_INF_4|1|5001",
		["delay"] = "1",
		["actor"] = "main",
		["condtion_next"] = "5001|1011",
		["action"] = "areaC",
		["type"] = "Area",
		["id"] = "1009",
	},
	["1010"] = {
		["actor"] = "me",
		["delay"] = "1.5",
		["param"] = "1",
		["action"] = "controlC",
		["type"] = "Player",
		["id"] = "1010",
	},
	["5001"] = {
		["actor"] = "main",
		["next"] = "1011",
		["param"] = "52666157",
		["action"] = "dialogC",
		["type"] = "Plot",
		["id"] = "5001",
	},
	["1011"] = {
		["condtion"] = "return getStorySysData('dy_guideGrowLocalCloseTalk')==0",
		["param"] = "UI_AREA_EquipForge_INF_2|1|5002",
		["actor"] = "main",
		["condtion_next"] = "5002|1012",
		["action"] = "areaC",
		["type"] = "Area",
		["id"] = "1011",
	},
	["5002"] = {
		["actor"] = "main",
		["next"] = "1012",
		["param"] = "52666158",
		["action"] = "dialogC",
		["type"] = "Plot",
		["id"] = "5002",
	},
	["1012"] = {
		["condtion"] = "return getStorySysData('dy_guideGrowLocalCloseTalk')==0",
		["param"] = "UI_AREA_EquipForge_INF_3|1|5003",
		["actor"] = "main",
		["condtion_next"] = "5003|1013",
		["action"] = "areaC",
		["type"] = "Area",
		["id"] = "1012",
	},
	["5003"] = {
		["actor"] = "main",
		["next"] = "1013",
		["param"] = "52666159",
		["action"] = "dialogC",
		["type"] = "Plot",
		["id"] = "5003",
	},
	["1013"] = {
		["condtion"] = "return getStorySysData('dy_guideGrowLocalCloseTalk')==0",
		["param"] = "UI_AREA_EquipForge_INF_1|1|5004",
		["actor"] = "main",
		["condtion_next"] = "5004|1014",
		["action"] = "areaC",
		["type"] = "Area",
		["id"] = "1013",
	},
	["5004"] = {
		["actor"] = "main",
		["next"] = "1014",
		["param"] = "52666160",
		["action"] = "dialogC",
		["type"] = "Plot",
		["id"] = "5004",
	},
	["1014"] = {
		["action"] = "endC",
		["type"] = "Story",
		["id"] = "1014",
		["actor"] = "main",
	},
}
return luaxml_script_Guide_EquipMake
