-- luaxml_script_Camera_C
local luaxml_script_Camera_C = {
	["1000"] = {
		["actor"] = "main",
		["next"] = "1001",
		["param"] = "",
		["action"] = "start",
		["type"] = "Story",
		["id"] = "1000",
	},
	["1001"] = {
		["actor"] = "me",
		["next"] = "1002",
		["param"] = "2",
		["action"] = "controlC",
		["type"] = "Player",
		["id"] = "1001",
	},
	["1002"] = {
		["actor"] = "main",
		["next"] = "1003",
		["param"] = "100;100|10",
		["action"] = "movePC",
		["type"] = "Camera_C",
		["id"] = "1002",
	},
	["1003"] = {
		["actor"] = "main",
		["next"] = "1004",
		["delay"] = "5",
		["param"] = "400000",
		["action"] = "buildC",
		["type"] = "Camera_C",
		["id"] = "1003",
	},
	["1004"] = {
		["actor"] = "main",
		["next"] = "1005",
		["delay"] = "3",
		["param"] = "2|10",
		["action"] = "fadeC",
		["type"] = "Camera_C",
		["id"] = "1004",
	},
	["1005"] = {
		["actor"] = "main",
		["next"] = "1006",
		["delay"] = "3",
		["param"] = "1|10",
		["action"] = "fadeC",
		["type"] = "Camera_C",
		["id"] = "1005",
	},
	["1006"] = {
		["actor"] = "main",
		["next"] = "1007",
		["param"] = "4;5|10",
		["action"] = "shakeC",
		["type"] = "Camera_C",
		["id"] = "1006",
	},
	["1007"] = {
		["actor"] = "me",
		["next"] = "1008",
		["param"] = "1",
		["action"] = "controlC",
		["type"] = "Player",
		["id"] = "1007",
	},
	["1008"] = {
		["action"] = "endC",
		["delay"] = "5",
		["type"] = "Story",
		["id"] = "1008",
		["actor"] = "main",
	},
}
return luaxml_script_Camera_C
