-- luaxml_script_Guide_EquipSteelsGain
local luaxml_script_Guide_EquipSteelsGain = {
	["1000"] = {
		["condtion"] = "return getStorySysData('dy_AllianceJoin')==1",
		["param"] = "",
		["actor"] = "main",
		["condtion_next"] = "1001|5002",
		["action"] = "start",
		["type"] = "Story",
		["id"] = "1000",
	},
	["1001"] = {
		["actor"] = "main",
		["next"] = "1002",
		["delay"] = "1",
		["param"] = "UI_AREA_MainUI_INF_2|2|5001",
		["action"] = "clickC",
		["type"] = "Arrow",
		["id"] = "1001",
	},
	["1002"] = {
		["actor"] = "main",
		["next"] = "1003",
		["delay"] = "1",
		["param"] = "UI_AREA_Alliance_INF_1|1|5001",
		["action"] = "clickC",
		["type"] = "Arrow",
		["id"] = "1002",
	},
	["1003"] = {
		["actor"] = "main",
		["next"] = "5001",
		["delay"] = "1",
		["param"] = "UI_AREA_AllianceShop_INF_1|1|5001",
		["action"] = "clickC",
		["type"] = "Arrow",
		["id"] = "1003",
	},
	["5001"] = {
		["actor"] = "main",
		["next"] = "1004",
		["delay"] = "1",
		["param"] = "52666183",
		["action"] = "dialogC",
		["type"] = "Plot",
		["id"] = "5001",
	},
	["1004"] = {
		["action"] = "endC",
		["type"] = "Story",
		["id"] = "1004",
		["actor"] = "main",
	},
	["5002"] = {
		["actor"] = "main",
		["next"] = "1004",
		["delay"] = "1",
		["param"] = "52666184",
		["action"] = "dialogC",
		["type"] = "Plot",
		["id"] = "5002",
	},
}
return luaxml_script_Guide_EquipSteelsGain
