-- luaxml_script_Guide_HeroData
local luaxml_script_Guide_HeroData = {
	["1000"] = {
		["actor"] = "main",
		["next"] = "1001",
		["param"] = "",
		["action"] = "start",
		["type"] = "Story",
		["id"] = "1000",
	},
	["1001"] = {
		["action"] = "hideC",
		["type"] = "MainUI",
		["id"] = "1001",
		["actor"] = "main",
		["next"] = "1002",
	},
	["1002"] = {
		["actor"] = "me",
		["next"] = "1003",
		["param"] = "2",
		["action"] = "controlC",
		["type"] = "Player",
		["id"] = "1002",
	},
	["1003"] = {
		["actor"] = "main",
		["next"] = "1004",
		["delay"] = "1",
		["param"] = "433000",
		["action"] = "buildC",
		["type"] = "Camera_C",
		["id"] = "1003",
	},
	["1004"] = {
		["actor"] = "main",
		["next"] = "1005;1006",
		["delay"] = "1",
		["param"] = "433000",
		["action"] = "clickBuildC",
		["type"] = "Build_C",
		["id"] = "1004",
	},
	["1005"] = {
		["actor"] = "me",
		["delay"] = "1.5",
		["param"] = "1",
		["action"] = "controlC",
		["type"] = "Player",
		["id"] = "1005",
	},
	["1006"] = {
		["actor"] = "main",
		["next"] = "1007",
		["delay"] = "1",
		["param"] = "UI_AREA_433000_PUW_3|1|5001",
		["action"] = "clickC",
		["type"] = "Arrow",
		["id"] = "1006",
	},
	["1007"] = {
		["action"] = "showC",
		["type"] = "MainUI",
		["id"] = "1007",
		["actor"] = "main",
		["next"] = "1008",
	},
	["1008"] = {
		["actor"] = "me",
		["next"] = "1009;1010",
		["param"] = "2",
		["action"] = "controlC",
		["type"] = "Player",
		["id"] = "1008",
	},
	["1009"] = {
		["actor"] = "main",
		["next"] = "1011",
		["delay"] = "1",
		["param"] = "UI_AREA_HeroSelect_INF_1|1|5001",
		["action"] = "clickC",
		["type"] = "Arrow",
		["id"] = "1009",
	},
	["1010"] = {
		["actor"] = "me",
		["delay"] = "1.5",
		["param"] = "1",
		["action"] = "controlC",
		["type"] = "Player",
		["id"] = "1010",
	},
	["1011"] = {
		["actor"] = "me",
		["next"] = "1012;1013",
		["param"] = "2",
		["action"] = "controlC",
		["type"] = "Player",
		["id"] = "1011",
	},
	["1012"] = {
		["actor"] = "me",
		["delay"] = "1.5",
		["param"] = "1",
		["action"] = "controlC",
		["type"] = "Player",
		["id"] = "1012",
	},
	["1013"] = {
		["condtion"] = "return getStorySysData('dy_guideGrowLocalCloseTalk')==0",
		["param"] = "UI_AREA_HeroData_INF_5|1|5001",
		["delay"] = "1",
		["actor"] = "main",
		["condtion_next"] = "5001|1014",
		["action"] = "areaC",
		["type"] = "Area",
		["id"] = "1013",
	},
	["5001"] = {
		["actor"] = "main",
		["next"] = "1010",
		["param"] = "52666154",
		["action"] = "dialogC",
		["type"] = "Plot",
		["id"] = "5001",
	},
	["1014"] = {
		["action"] = "endC",
		["type"] = "Story",
		["id"] = "1014",
		["actor"] = "main",
	},
}
return luaxml_script_Guide_HeroData
